### ISSUE TITLE
pip install issues

### ISSUE THREAD

**Issue by JJTimmons** [Edinburgh-Genome-Foundry/DnaChisel#9]
Hello! The library looks great. I like the multi-layered constraints. They would work perfectly for a project I am working on right now.

I am, however, having some issues with `pip3 install`'ing the package.

- python2 `pip install` totally fails because of some weazyprint version issue (which is fine for me, just sharing)
- `pip3 install` doesn't make the module global. I can't import it elsewhere. I do not know why right now
- git cloning the repo and `pip3 install -e .`'ing it works for adding it as a global dependency, but I still  get warnings about versions when importing:

![Screen Shot 2019-03-25 at 9 47 09 AM](https://user-images.githubusercontent.com/13923102/54924763-70e35480-4ee3-11e9-94f0-78451c5148a6.png)

If I get time and find a fix I'll submit a PR. My first approach would be to pin the dependencies (particularly around weazy) in `setup.py` (move to requirements.txt).

In the Readme the install instructions make the plot package installation look optional, but then in `setup.py` `find_packages` is used, which I think is installing weazyprint, etc) even though I have no interest in the visual reports (or the pdf_report tbh). I looks like `dna_chisel` has close to 35 dependencies right now which is a bit excessive. The rest of my application has ~5. And things like `defusedxml`, `webencodings`, `CairoSVG` are all being added

**Comment by Zulko** [comment]
Thanks for the report and sorry for that, I recently (two weeks ago) made the PDF reporting un-optional, and it comes with some heavier dependencies. I'm thinking of making them optional again.

Could you please provide full errors for python2 ? Do you absolutely need python2 compatibility ?

I am not sure what you mean by "pip3 install doesn't make the module global", that one is really weird, could you provide the details ?

**Comment by JJTimmons** [comment]
Thanks for quick reply. I do not need python2, no worries at all about that (just mentioned because I was testing python2 to see if I get it to work).

Sharing full python3 example below (this was from a fresh machine w/o any of the peer dependencies cached) 

The problem line looks to be this one:

```
weasyprint 46 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
```

```
python3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dnachisel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dnachisel'
>>> exit(0
... )
~$ python3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
~$ pip3 install dnachisel
Collecting dnachisel
  Downloading https://files.pythonhosted.org/packages/49/d5/8531e5002b8953c1f00bd3ca8160c61860d1e5694af793ac9db1932d530c/dnachisel-1.0.2.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 16.7MB/s 
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dnachisel) (1.16.0)
Collecting Biopython (from dnachisel)
  Downloading https://files.pythonhosted.org/packages/f0/6f/388e730f61ca76dbc89885e102d6105124151c3291e8ac0a08be51410afd/biopython-1.73-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 12.3MB/s 
Collecting proglog (from dnachisel)
  Downloading https://files.pythonhosted.org/packages/fe/ab/4cb19b578e1364c0b2d6efd6521a8b4b4e5c4ae6528041d31a2a951dd991/proglog-0.1.9.tar.gz
Collecting docopt (from dnachisel)
  Using cached https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting flametree (from dnachisel)
  Downloading https://files.pythonhosted.org/packages/96/8b/43f80613234c04f3a0990ccbd018788de2d54b23191b7438ec49b72e2dd0/flametree-0.1.10.tar.gz
Collecting pdf_reports (from dnachisel)
  Downloading https://files.pythonhosted.org/packages/cf/78/72271e749b8712bc2328c3939edef6f2cd3ce9fe6c9f1ce5e5db55ecf5bc/pdf_reports-0.2.4.tar.gz (121kB)
    100% |████████████████████████████████| 122kB 17.8MB/s 
Collecting sequenticon (from dnachisel)
  Downloading https://files.pythonhosted.org/packages/95/bf/db6b7804f2e7553fae2e19bd391dcff8ff3ce29e34ba1377e4ba4e166acf/sequenticon-0.1.4.tar.gz
Collecting python_codon_tables (from dnachisel)
  Downloading https://files.pythonhosted.org/packages/01/63/3129966602d4813677a7e0977a1ccd525cf93024d53c4081f8f98f1bcd84/python_codon_tables-0.1.8.tar.gz
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from proglog->dnachisel) (4.28.1)
Collecting pypugjs (from pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/ee/f7/b2b494ef67f35e8db63bbac5e086dcfae52d38d43f23b129e612e912acb8/pypugjs-5.8.0-py2.py3-none-any.whl
Collecting jinja2 (from pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 31.6MB/s 
Collecting weasyprint (from pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/5d/af/e46f6e33d37edc39ff0a19f20e3d1fb3e1650adfdbf3ccd73d10a1cfce21/WeasyPrint-46-py3-none-any.whl (347kB)
    100% |████████████████████████████████| 348kB 14.2MB/s 
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pdf_reports->dnachisel) (4.6.3)
Collecting pandas (from pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/fc/43/fd867e3347559845c8f993059d410c50a1e18709f1c4d4b3b47323a06a37/pandas-0.24.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (15.9MB)
    100% |████████████████████████████████| 15.9MB 3.0MB/s 
Collecting Markdown (from pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/7a/6b/5600647404ba15545ec37d2f7f58844d690baf2f81f3a60b862e48f29287/Markdown-3.0.1-py2.py3-none-any.whl (89kB)
    100% |████████████████████████████████| 92kB 12.8MB/s 
Collecting pydenticon (from sequenticon->dnachisel)
  Downloading https://files.pythonhosted.org/packages/76/fa/3085252e2cfd8353624142fb18ca007a2ce4fe199a1440ea3c85ec5b8620/pydenticon-0.3.1.tar.gz
Collecting snapgene_reader (from sequenticon->dnachisel)
  Downloading https://files.pythonhosted.org/packages/f6/90/bfd3cc66c6e5045f4156b695708dcec715e9ff18d4aef9493fd7f966f5aa/snapgene_reader-0.1.15.tar.gz
Requirement already satisfied: six in ./Library/Python/3.7/lib/python/site-packages (from pypugjs->pdf_reports->dnachisel) (1.11.0)
Requirement already satisfied: chardet in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pypugjs->pdf_reports->dnachisel) (3.0.4)
Collecting MarkupSafe>=0.23 (from jinja2->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/ce/c6/f000f1af136ef74e4a95e33785921c73595c5390403f102e9b231b065b7a/MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl
Collecting cffi>=0.6 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/6b/af/e39e89ecbfb676c6aa5855b1795bb207f4005187495c8d40e26b5fb51bfa/cffi-1.12.2-cp37-cp37m-macosx_10_9_x86_64.whl (168kB)
    100% |████████████████████████████████| 174kB 21.2MB/s 
Collecting cssselect2>=0.1 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/12/e2/91fcd4cd32545beec6e11628d64d3e20f11b5a95dd1ccf3216fd69f176b7/cssselect2-0.2.1-py2.py3-none-any.whl
Collecting CairoSVG>=1.0.20 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/4a/f3/4abcf0c55f51af5175fcddc893c4026c1c996f49ac4cab9eae6f9b7c89c3/CairoSVG-2.3.0-py3-none-any.whl (51kB)
    100% |████████████████████████████████| 51kB 24.7MB/s 
Collecting html5lib>=0.999999999 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 40.0MB/s 
Collecting setuptools>=39.2.0 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 16.8MB/s 
Collecting tinycss2>=0.5 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/94/2c/4e501f9c351343c8ba10d70b5a7ca97cdab2690af043a6e52ada65b85b6b/tinycss2-1.0.2-py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 30.4MB/s 
Collecting cairocffi>=0.9.0 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/0f/0f/7e21b5ddd31b610e46a879c0d21e222dd0fef428c1fc86bbd2bd57fed8a7/cairocffi-1.0.2.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 14.6MB/s 
  Requested cairocffi>=0.9.0 from https://files.pythonhosted.org/packages/0f/0f/7e21b5ddd31b610e46a879c0d21e222dd0fef428c1fc86bbd2bd57fed8a7/cairocffi-1.0.2.tar.gz#sha256=01ac51ae12c4324ca5809ce270f9dd1b67f5166fe63bd3e497e9ea3ca91946ff (from weasyprint->pdf_reports->dnachisel), but installing version file-.cairocffi-VERSION
Collecting Pyphen>=0.8 (from weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/15/82/08a3629dce8d1f3d91db843bb36d4d7db6b6269d5067259613a0d5c8a9db/Pyphen-0.9.5-py2.py3-none-any.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 5.5MB/s 
Collecting pytz>=2011k (from pandas->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 20.8MB/s 
Requirement already satisfied: python-dateutil>=2.5.0 in ./Library/Python/3.7/lib/python/site-packages (from pandas->pdf_reports->dnachisel) (2.7.3)
Collecting Pillow (from pydenticon->sequenticon->dnachisel)
  Downloading https://files.pythonhosted.org/packages/c9/ed/27cc92e99b9ccaa0985a66133baeea7e8a3371d3c04cfa353aaa3b81aac1/Pillow-5.4.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 5.8MB/s 
Requirement already satisfied: xmltodict in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from snapgene_reader->sequenticon->dnachisel) (0.11.0)
Collecting html2text (from snapgene_reader->sequenticon->dnachisel)
  Downloading https://files.pythonhosted.org/packages/16/20/de2b458ef434713053dd83209a03a5431ebe0527c8e14d9ae7838ff67d8a/html2text-2018.1.9-py3-none-any.whl
Collecting pycparser (from cffi>=0.6->weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 25.5MB/s 
Collecting defusedxml (from CairoSVG>=1.0.20->weasyprint->pdf_reports->dnachisel)
  Downloading https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from html5lib>=0.999999999->weasyprint->pdf_reports->dnachisel) (0.5.1)
weasyprint 46 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
Installing collected packages: Biopython, proglog, docopt, flametree, pypugjs, MarkupSafe, jinja2, pycparser, cffi, setuptools, tinycss2, cssselect2, defusedxml, cairocffi, Pillow, CairoSVG, html5lib, Pyphen, weasyprint, pytz, pandas, Markdown, pdf-reports, pydenticon, html2text, snapgene-reader, sequenticon, python-codon-tables, dnachisel
  Running setup.py install for proglog ... done
  Running setup.py install for docopt ... done
  Running setup.py install for flametree ... done
  Running setup.py install for pycparser ... done
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
  Running setup.py install for cairocffi ... done
  Running setup.py install for pdf-reports ... done
  Running setup.py install for pydenticon ... done
  Running setup.py install for snapgene-reader ... done
  Running setup.py install for sequenticon ... done
  Running setup.py install for python-codon-tables ... done
  Running setup.py install for dnachisel ... done
Successfully installed Biopython-1.73 CairoSVG-2.3.0 Markdown-3.0.1 MarkupSafe-1.1.1 Pillow-5.4.1 Pyphen-0.9.5 cairocffi-1.0.2 cffi-1.12.2 cssselect2-0.2.1 defusedxml-0.5.0 dnachisel-1.0.2 docopt-0.6.2 flametree-0.1.10 html2text-2018.1.9 html5lib-1.0.1 jinja2-2.10 pandas-0.24.2 pdf-reports-0.2.4 proglog-0.1.9 pycparser-2.19 pydenticon-0.3.1 pypugjs-5.8.0 python-codon-tables-0.1.8 pytz-2018.9 sequenticon-0.1.4 setuptools-40.8.0 snapgene-reader-0.1.15 tinycss2-1.0.2 weasyprint-46
~$ python3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dnachisel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/__init__.py", line 1, in <module>
    from .DnaOptimizationProblem import (DnaOptimizationProblem, NoSolutionError,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/DnaOptimizationProblem.py", line 19, in <module>
    from .reports.optimization_reports import (write_optimization_report,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/reports/__init__.py", line 3, in <module>
    from .optimization_reports import (write_no_solution_report,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/reports/optimization_reports.py", line 13, in <module>
    from sequenticon import sequenticon
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sequenticon/__init__.py", line 5, in <module>
    from .sequenticon import (sequenticon,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sequenticon/sequenticon.py", line 8, in <module>
    from pdf_reports import pug_to_html, write_report
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pdf_reports/__init__.py", line 1, in <module>
    from .pdf_reports import (pug_to_html, write_report, ReportWriter, GLOBALS,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pdf_reports/pdf_reports.py", line 3, in <module>
    from weasyprint import HTML, CSS
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/__init__.py", line 441, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 29, in <module>
    from . import computed_values
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/css/computed_values.py", line 17, in <module>
    from .. import text
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/text.py", line 14, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cairocffi/__init__.py", line 39, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2', 'cairo.so.2')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cairocffi/__init__.py", line 36, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2
>>> from dnachisel import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/__init__.py", line 1, in <module>
    from .DnaOptimizationProblem import (DnaOptimizationProblem, NoSolutionError,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/DnaOptimizationProblem.py", line 19, in <module>
    from .reports.optimization_reports import (write_optimization_report,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/reports/__init__.py", line 3, in <module>
    from .optimization_reports import (write_no_solution_report,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dnachisel/reports/optimization_reports.py", line 13, in <module>
    from sequenticon import sequenticon
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sequenticon/__init__.py", line 5, in <module>
    from .sequenticon import (sequenticon,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sequenticon/sequenticon.py", line 8, in <module>
    from pdf_reports import pug_to_html, write_report
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pdf_reports/__init__.py", line 1, in <module>
    from .pdf_reports import (pug_to_html, write_report, ReportWriter, GLOBALS,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pdf_reports/pdf_reports.py", line 3, in <module>
    from weasyprint import HTML, CSS
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/__init__.py", line 441, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 29, in <module>
    from . import computed_values
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/css/computed_values.py", line 17, in <module>
    from .. import text
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weasyprint/text.py", line 14, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cairocffi/__init__.py", line 39, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2', 'cairo.so.2')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cairocffi/__init__.py", line 36, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2
```

**Comment by JJTimmons** [comment]
re: the dependency count thing, part of it is that more dependencies mean more interactions that could go wrong (example this weazyprint thing). Majority of my XP is with node/npm, but, in general, the fewer dependencies a library has the better. They're quicker to install and have a smaller footprint. Also from a security point of view, it's hard to trust every one of these dependencies. Obviously I don't think it's the case here, but any on of these dependencies could have a security vulnerabiliy (sending proprietary seq data off to a remote server) and in installing just dnachisel I have to trust 35x other packages as well

**Comment by JJTimmons** [comment]
unrelated but this is a really cool library that you made: https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/graphs/contributors

We had to setup something similar in JS awhile ago, but I like the interface you already made in that module

**Comment by Zulko** [comment]
I modified the requirements system so that ``pip install dnachisel`` will install the bare minimum while ``pip install dnachisel[reports]`` will install everything. The test suite is only configured for when the full requirements are there, but I have made some manual tests and the library seems to run ok with just the partial requirements.

I am leaving the issue open in case you run into troubles in the short term.

Regarding the dependency count: I agree with the security issue but 95% of my dependencies are either from this repository or from very popular projects so it should be fine. I agree with the idea that cross-compatibility interactions that could go wrong: because I am very active on these projects I just go with the last version for every piece of software. In practice, there is a backwards-compatibility issue due to an updated third-party library every 6 months, which I fix quickly enough. I'm not a big fan of freezing dependencies in Python, it's not as prettily managed as in Node/NPM. Regarding the footprint, it's low priority for me because it is just backend code, and Python's scientific libraries can be huge anyways.

Regarding codon_usage_tables, I think it could be turned into a JS library, the same way I turned it into a python library, but I never tried. Ideally, this would be done in the same repository, without touching any other file, just by adding a package.json file at the root and a JS script to fetch the tables (or fetch data from the kazusa.jp website directly).

**Comment by JJTimmons** [comment]
nice and sounds good. Will try it later this afternoon or tomorrow and let you know how it goes. Right now I'm just doing CAI with your python_codon_tables module, but it would be nice to layer in BsaI avoidance and [hairpin avoidance in the 5' end](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3902468/).

I agree that most of the dependencies are totally fine/have zero-cost. Almost made an edit to say that packages like setuptools and numpy might as well be standard. It's really just the installing of HTML/CSS/PDF dependencies that I didn't feel great about, but this refactor looks like it address that. Thanks for the quick changes!

**Comment by Zulko** [comment]
Great, please let me know if you meet difficulties while defining problems with DnaChisel (I am really interested in how "discoverable" and easy to understand the library is at this stage).

**Comment by Zulko** [comment]
Hey does it work like you want now? Can I close this issue?

**Comment by simone-pignotti** [comment]
`pip install dnachisel[reports]` works great for me on macOS after `brew install pango`

**Comment by Zulko** [comment]
@simone-pignotti I'll add the recommendation to the README :+1:
